---
  - name: New VM
    hosts: all
    become: yes
    become_user: root
    gather_facts: No
    tasks:
      - name: Install a list of packages 
        yum:
          name: "{{ packages }}"
        vars:
          packages:
          - vim
          - net-tools
          - wget
          - telnet
          - git

      - name: Disable Selinux
        shell: |
          setenforce 0
          sed -i --follow-symlinks 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux
     
      - name: Disable Firewall  
        service:
          name: firewalld
          state: stopped
          enabled: no

      - name: Update susctl setting for Kubernetes networking
        shell: |
          cat >>/etc/sysctl.d/kubernetes.conf<<EOF
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF

