---
- hosts: kubernetes-worker-nodes
  vars_files:
  - env_variables
  tasks:

  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token
 
  - name: Creating sh with token
    shell: tail -2 join_token > join.sh

  - name: Joining worker nodes with kubernetes master
    shell: sh join.sh