---
- name: Install docker
  gather_facts: No
  hosts: all

  tasks:
    - name: Install Requere package
      yum:
          name: "{{ packages }}"
      vars:
          packages:
          - yum-utils
          - lvm2
          - device-mapper-persistent-data

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      yum:
          name: docker-ce-19.03.12 
    
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
